services:
  mechmate:
    build: .
    container_name: mechmate
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      # Persistent data storage
      - mechmate_data:/app/data
      # Optional: bind mount for easier file access
      # - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: set resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mechmate_data:
    driver: local

# Optional: reverse proxy setup with Traefik
# Uncomment below if you're using Traefik for SSL termination
#
# networks:
#   default:
#     external:
#       name: traefik
#
# services:
#   mechmate:
#     # ... (add to existing service)
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.mechmate.rule=Host(`mechmate.yourdomain.com`)"
#       - "traefik.http.routers.mechmate.entrypoints=websecure"
#       - "traefik.http.routers.mechmate.tls.certresolver=letsencrypt"
#       - "traefik.http.services.mechmate.loadbalancer.server.port=3000"